/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package primerossiguientes;

import java.awt.Cursor;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.edisoncor.gui.progressBar.ProgressBarRect;

/**
 *
 * @author por_s
 */
public class Sintactico extends javax.swing.JFrame {

    public static Procesos pcs;

    /**
     * Creates new form Sintactico
     */
    public Sintactico() {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/17854 - cubes module modules.png"));
        this.setIconImage(icono);

        initComponents();

        this.setLocationRelativeTo(null);
        this.setTitle("ProcesosSintacticos");
        // this.setResizable(false);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);

        pcs = null;
        //Bontones
        this.btnGramatica.setEnabled(true);
        this.btnPrimeros.setEnabled(false);
        this.btnSiguientes.setEnabled(false);
        this.btnAmbiguedad.setEnabled(false);
        this.btnTerminar.setEnabled(false);
        this.btnTabla.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGramatica = new javax.swing.JButton();
        btnPrimeros = new javax.swing.JButton();
        btnSiguientes = new javax.swing.JButton();
        btnAmbiguedad = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();
        btnTabla = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        progressBarRect1 = new org.edisoncor.gui.progressBar.ProgressBarRect();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGramatica.setText("Cargar Gramatica separada");
        btnGramatica.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGramatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGramaticaActionPerformed(evt);
            }
        });

        btnPrimeros.setText("Buscar primeros");
        btnPrimeros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPrimeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimerosActionPerformed(evt);
            }
        });

        btnSiguientes.setText("Buscar siguientes");
        btnSiguientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSiguientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguientesActionPerformed(evt);
            }
        });

        btnAmbiguedad.setText("Buscar ambiguedades");
        btnAmbiguedad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAmbiguedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmbiguedadActionPerformed(evt);
            }
        });

        btnTerminar.setText("Terminar");
        btnTerminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        btnTabla.setText("Llenar tabla predictiva");
        btnTabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGramatica, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrimeros, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSiguientes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAmbiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 304, Short.MAX_VALUE))
                    .addComponent(progressBarRect1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressBarRect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGramatica)
                    .addComponent(btnPrimeros)
                    .addComponent(btnSiguientes)
                    .addComponent(btnAmbiguedad)
                    .addComponent(btnTerminar)
                    .addComponent(btnTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAmbiguedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmbiguedadActionPerformed
        pcs.procesoAmbieguedad();
        Mensaje.exito(this, "Proceso realizado con exito");
        this.btnGramatica.setEnabled(true);
        this.btnPrimeros.setEnabled(true);
        this.btnSiguientes.setEnabled(true);
        this.btnAmbiguedad.setEnabled(true);
        this.btnTerminar.setEnabled(true);
        this.btnTabla.setEnabled(false);
    }//GEN-LAST:event_btnAmbiguedadActionPerformed
    int numGram = 0;

    private void btnGramaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGramaticaActionPerformed

        try {
            JFileChooser selecciona = new JFileChooser();  //crea objeto file chooser
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo .txt", "txt", "txt");  //solo muestra archivos .mp3 en file chocer
            selecciona.setFileFilter(filtro);  //se agrega el filtro al file chooser
            selecciona.showOpenDialog(this);   //sin esto me marcaba error :v
            File archivoExtraido = selecciona.getSelectedFile(); //obtiene el archivo en la variable archivo
            String url; //borra la ruta para evitar que se quede una anterior

            String etiquetaNombre;
            if (archivoExtraido != null) // si no se selecciono ningun archivo no hace nada
            {

                url = archivoExtraido.getCanonicalPath(); //obtiene la ruta del archivo
                etiquetaNombre = archivoExtraido.getName();//obtiene el nombre del archivo/cancion                

                String s = "";
                ArrayList<String> ar = ManipulaArchivos.cargar(url);

                if (ar != null) {
                    for (int i = 0; i < ar.size(); i++) {
                        s += ar.get(i);
                    }
                    //Escribiendo el texto en el editor

                    JTextPane txt = new JTextPane();
                    jScrollPane1.setViewportView(txt);
                    txt.setText(s);
                    Mensaje.exito(this, "Archivo extraido con exito");
                    this.btnGramatica.setEnabled(true);
                    this.btnPrimeros.setEnabled(true);
                    this.btnSiguientes.setEnabled(false);
                    this.btnAmbiguedad.setEnabled(false);
                    this.btnTerminar.setEnabled(false);
                    this.btnTabla.setEnabled(false);
                    pcs = new Procesos(url);
                    pcs.setPr(progressBarRect1);
                } else {
                    Mensaje.advertencia(this, "No se ha extraido el archivo por cancelacion");
                }

            }

        } catch (HeadlessException | IOException e) {
            Mensaje.error(this, "Ha ocurrido un error al abrir el archivo");
        }


    }//GEN-LAST:event_btnGramaticaActionPerformed

    private void btnPrimerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimerosActionPerformed
        pcs.procesosPrimeros.start();
        progressBarRect1.setValue(0);
        this.btnGramatica.setEnabled(true);
        this.btnPrimeros.setEnabled(true);
        this.btnSiguientes.setEnabled(true);
        this.btnAmbiguedad.setEnabled(false);
        this.btnTerminar.setEnabled(false);
        this.btnTabla.setEnabled(false);
    }//GEN-LAST:event_btnPrimerosActionPerformed

    private void btnSiguientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguientesActionPerformed

        String inicio = JOptionPane.showInputDialog(this, "Introduce el objeto raiz de la gramatica", "Inicio", 1);
        if (inicio != null) {
            if (inicio.isEmpty()) {
                Mensaje.advertencia(this, "No se ha introducido ningun valor ");
            } else {

                setCursor(new Cursor(Cursor.WAIT_CURSOR));
                if (pcs.procesoSiguientes(inicio)) {
                    Mensaje.exito(this, "Proceso realizado con exito");
                    this.btnGramatica.setEnabled(true);
                    this.btnPrimeros.setEnabled(true);
                    this.btnSiguientes.setEnabled(true);
                    this.btnAmbiguedad.setEnabled(true);
                    this.btnTerminar.setEnabled(false);
                    this.btnTabla.setEnabled(false);
                    setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                } else {
                    setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                    Mensaje.advertencia(this, "La entrada no aparece en los registros, por favor verifique el dato ");
                }
            }
        }


    }//GEN-LAST:event_btnSiguientesActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed

        javax.swing.JTable tablaLexemas = new javax.swing.JTable();

        tablaLexemas.setFont(new java.awt.Font("Arial", 0, 14));

        tablaLexemas.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String[]{
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        //
        //come

        tablaLexemas.getTableHeader().setReorderingAllowed(false);
        tablaLexemas.setRowHeight(20);

        tablaLexemas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        DefaultTableModel model;
        String[] columnas = {"Objeto No terminal", "Primeros", "Siguientes", "Ambiguedad"};
        model = new DefaultTableModel(null, columnas);
        String[] filas = new String[4];

        for (int i = 0; i < pcs.getObjPyS().size(); i++) {
            //textoMostrar += " " +  + "\t" +  + "\t" + lexemas.get(i).getNumToken() + "\t" + lexemas.get(i).getRenglon() + "\n";

            filas[0] = pcs.getObjPyS().get(i).getObjNT();
            filas[1] = pcs.getObjPyS().get(i).getPrimeros();
            filas[2] = pcs.getObjPyS().get(i).getSiguientes();
           if(pcs.getObjPyS().get(i).isAmbiguedad()){
               filas[3] = "Si"; 
           }else{
               filas[3] = "No";
           }
            //String.valueOf(pcs.getObjPyS().get(i).isAmbiguedad());

            model.addRow(filas);
        }
        tablaLexemas.setModel(model);

        jScrollPane1.setViewportView(tablaLexemas);

        this.btnGramatica.setEnabled(true);
        this.btnPrimeros.setEnabled(true);
        this.btnSiguientes.setEnabled(true);
        this.btnAmbiguedad.setEnabled(true);
        this.btnTerminar.setEnabled(true);
        this.btnTabla.setEnabled(true);
        Mensaje.exito(this, "Proceso terminado con exito");
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void btnTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaActionPerformed
        this.btnGramatica.setEnabled(true);
        this.btnPrimeros.setEnabled(true);
        this.btnSiguientes.setEnabled(true);
        this.btnAmbiguedad.setEnabled(true);
        this.btnTerminar.setEnabled(true);
        this.btnTabla.setEnabled(true);
    }//GEN-LAST:event_btnTablaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmbiguedad;
    private javax.swing.JButton btnGramatica;
    private javax.swing.JButton btnPrimeros;
    private javax.swing.JButton btnSiguientes;
    private javax.swing.JButton btnTabla;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.progressBar.ProgressBarRect progressBarRect1;
    // End of variables declaration//GEN-END:variables
}
